- name: Criando Diretorio de Backup
  file:
    path: "/backup/moodle-{{ env }}/bkp_{{ansible_date_time.date}}"
    owner: root
    group: root
    mode: '0775'
    state: directory
  tags:
  - backup

- name: Realizando Backup da Aplicacao
  archive:
    path: 
    - "/opt/moodle-{{ env }}/app"
    dest: "/backup/moodle-{{ env }}/bkp_{{ansible_date_time.date}}/app_{{ansible_date_time.date}}.tar.bz2"
    format: bz2
  tags:
  - backup

- name: Realizando Backup do Bando de Dados
  archive:
    path:
    - "/opt/moodle-{{ env }}/mariadb"
    dest: "/backup/moodle-{{ env }}/bkp_{{ansible_date_time.date}}/mariadb_{{ansible_date_time.date}}.tar.bz2"
    format: bz2
  tags:
  - backup
